# Generated by Django 5.1.5 on 2025-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='full_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
